leader_key = "h"
leader_key_mods = "cmd,alt,ctrl,shift" # optional, default "", not recommended - a dedicated leader key is better
auto_reload = false
toast_on_reload = true
show_ui = true

[h]
label = "Hammerflow"
v = ["Visual Studio Code", "VS Code"]
